---

common_packages:
  - sudo
  - htop
  - mc
  - git
  - apt-transport-https
  - python-setuptools # easy_install (necessary for install python pip)


debian_release: jessie
certs_ca_password: 'e5t6#2r3041Zmo0Ai3c70zv81x3*ZBXn'
