---

- name: creates directories
  file: 
    state: directory
    path: '{{ item }}'
  with_items:
    - '/etc/consul'
    - '{{ docker_consul_tls_dir }}'
    - '/var/consul'


- name: uploads certifications
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0400
    owner: root
  with_items:
    - { src: 'certs/consul/ca.cert', dest: '{{ docker_consul_tls_ca_cert_file }}' }
    - { src: 'certs/consul/consul.cert', dest: '{{ docker_consul_tls_server_cert_file }}' }
    - { src: 'certs/consul/consul.key', dest: '{{ docker_consul_tls_server_key_file }}' }
  notify:
    # restart consul if certifications changes
    - restart consul


- name: uploads configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'config.json.j2', dest: '/etc/consul/config.json' }
  notify:
    # restart consul if configuration changes
    - restart consul


# Fir for: One or more undefined variables: 'ansible_docker0' is undefined
- name: updates facts if docker0 is not defined
  action: setup
  when: ansible_docker0 is not defined


- name: retrieves and launches 'consul' image
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_consul_image }}'
    ports:
      # Used by servers to handle incoming requests from other agents (TCP only).
      - '{{ ansible_eth0.ipv4.address }}:8300:8300'
      # Used to handle gossip in the LAN. Required by all agents (TCP and UDP).
      - '{{ ansible_eth0.ipv4.address }}:8301:8301'
      - '{{ ansible_eth0.ipv4.address }}:8301:8301/udp'
      # Used by servers to gossip over the WAN to other servers (TCP and UDP).
      - '{{ ansible_eth0.ipv4.address }}:8302:8302'
      - '{{ ansible_eth0.ipv4.address }}:8302:8302/udp'
      # Used by all agents to handle RPC from the CLI (TCP only).
      - '{{ ansible_eth0.ipv4.address }}:8400:8400'
      # Used by clients to talk to the HTTP/HTTPS API (TCP only).
      # - '{{ ansible_eth0.ipv4.address }}:8500:8500'
      # - '{{ ansible_eth0.ipv4.address }}:8543:8543'
      - '8500:8500'
      - '8543:8543'
      # Used to resolve DNS queries (TCP? and UDP).
      - '{{ ansible_docker0.ipv4.address }}:53:53/tcp'
      - '{{ ansible_docker0.ipv4.address }}:53:53/udp'
    volumes:
      # to support persistent storage
      - '/var/consul:/data'
      # configuration file
      - '/etc/consul/config.json:/etc/consul.d/server/config.json:ro'
      # ssl
      - '{{ docker_consul_tls_dir }}:/etc/consul.d/ssl/'
    hostname: '{{ ansible_hostname }}'
    name: consul
    command: '-advertise {{ ansible_eth0.ipv4.address }} {% if docker_consul_join == ansible_eth0.ipv4.address %} -bootstrap-expect 3 {% else %} -join {{ docker_consul_join }} {% endif %} -config-file /etc/consul.d/server/config.json'
    env:
      # variables for consul
      SERVICE_8500_NAME: 'consul-api'
      SERVICE_53_NAME: 'consul-dns'
      SERVICE_TAGS: '{{ ansible_hostname }}'
    state: started
    # will be checked for a newer version of the image each time the task executes
    pull: always
    # try to restart if the container exits
    restart_policy: always
    # it will try to restart 3 times before giving up
    restart_policy_retry: 3

